server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    mc.server.net: Auth
  host: 0.0.0.0:25565
  max_players: 50
  motd: '&2[&aProxy Sunucusu&2] &aanksoft.net'
  ping_passthrough: false
  priorities:
  - Auth
  - Lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25577
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.list
  - bungeecord.command.find
  - bungeecord.command.send
  - flamecord.usage
  default:
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: -1
prevent_proxy_connections: false
timeout: 17000
player_limit: -1
ip_forward: true
groups:
  cheraphp:
  - admin
remote_ping_timeout: 5000
connection_throttle: -1
log_commands: false
stats: 94da181c-04f9-484e-af34-7a44e4c13862
online_mode: true
forge_support: true
disabled_commands:
- DISABLED
servers:
  Auth:
    address: localhost:XXXXX
    motd: '&2[&Çakma Lobi&2] &aanksoft.net'
    restricted: false
  Lobby:
    address: localhost:XXXXXX
    motd: '&2[&Lobi&2] &aanksoft.net'
    restricted: false
